name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: -rltgoDzvO --delete
          SOURCE: ./
          REMOTE_HOST: 121.40.19.111
          REMOTE_USER: root
          TARGET: /usr/share/nginx/html
          EXCLUDE:
